INSERT INTO PRODUCTOS (ID, CALIFICACION, CANTIDAD, CATEGORIA, DESCRIPTION, DISPONIBLE, NOMBRE, PRECIO) VALUES (0, 3, 1, 1, 'ASD', true, 'pepe', 10);
INSERT INTO PRODUCTOS (ID, CALIFICACION, CANTIDAD, CATEGORIA, DESCRIPTION, DISPONIBLE, NOMBRE, PRECIO) VALUES (1, 2, 20, 5, 'ASGAGD', FALSE, 'JUAN', 6);
INSERT INTO PRODUCTOS (ID, CALIFICACION, CANTIDAD, CATEGORIA, DESCRIPTION, DISPONIBLE, NOMBRE, PRECIO) VALUES (2, 1, 18, 9, 'ASGGHHHAAD', true, 'DON', 79);
INSERT INTO NURIAPRUEBA (ID , NAME, AGE, HOBBIES, HEIGHT, WEIGHT) VALUES (0, 'AFJF', 4, 'AFKAK', 669, 52);
INSERT INTO NURIAPRUEBA (ID , NAME, AGE, HOBBIES, HEIGHT, WEIGHT) VALUES (1, 'antonia', 4, 'java', 709, 10000);
INSERT INTO NURIAPRUEBA (ID , NAME, AGE, HOBBIES, HEIGHT, WEIGHT) VALUES (2, 'pepe', 4, '50 sombras de cristian', 669, 76);

