INSERT INTO PRODUCTOS (ID, CALIFICACION, CANTIDAD, CATEGORIA, DESCRIPTION, DISPONIBLE, NOMBRE, PRECIO) VALUES (0, 3, 1, 1, 'ASD', true, 'pepe', 10);
INSERT INTO PRODUCTOS (ID, CALIFICACION, CANTIDAD, CATEGORIA, DESCRIPTION, DISPONIBLE, NOMBRE, PRECIO) VALUES (1, 2, 20, 5, 'ASGAGD', FALSE, 'JUAN', 6);
INSERT INTO PRODUCTOS (ID, CALIFICACION, CANTIDAD, CATEGORIA, DESCRIPTION, DISPONIBLE, NOMBRE, PRECIO) VALUES (2, 1, 18, 9, 'ASGGHHHAAD', true, 'DON', 79);
