INSERT INTO PRODUCTOS (ID, CALIFICACION, CANTIDAD, CATEGORIA, DESCRIPCION, DISPONIBLE, NOMBRE, PRECIO) VALUES (1, 3, 1, 1, 'ASD', true, 'pepe', 10);
INSERT INTO PRODUCTOS (ID, CALIFICACION, CANTIDAD, CATEGORIA, DESCRIPCION, DISPONIBLE, NOMBRE, PRECIO) VALUES (2, 2, 20, 5, 'ASGAGD', FALSE, 'JUAN', 6);
INSERT INTO PRODUCTOS (ID, CALIFICACION, CANTIDAD, CATEGORIA, DESCRIPCION, DISPONIBLE, NOMBRE, PRECIO) VALUES (3, 1, 18, 9, 'ASGGHHHAAD', true, 'DON', 79);

INSERT INTO COMPRADORES (BUYER_ID, EDAD, NOMBRE, NUMERO_DE_COMPRAS) VALUES (1, 12, 'PEPE' , 9);
INSERT INTO COMPRADORES (BUYER_ID, EDAD, NOMBRE, NUMERO_DE_COMPRAS) VALUES (2, 15, 'POPI' , 0);
INSERT INTO COMPRADORES (BUYER_ID, EDAD, NOMBRE, NUMERO_DE_COMPRAS) VALUES (3, 90, 'PIPO' , 3);

INSERT INTO VENDEDORES ( ID, NOMBRE, DNI, EDAD, NUMERO_DE_VENTAS) VALUES (1, 'JAJA', '4141414T' , 23 , 4);
INSERT INTO VENDEDORES ( ID, NOMBRE, DNI, EDAD, NUMERO_DE_VENTAS) VALUES (2,  'AJAJA', '562145Y' , 7 , 10);
INSERT INTO VENDEDORES ( ID, NOMBRE, DNI, EDAD, NUMERO_DE_VENTAS) VALUES ( 3,'JAJAJAJA', '71257U' , 15 , 8);


